apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  labels:
    wave: "01"
  annotations:
    argocd.argoproj.io/sync-wave: "01"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: minio
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 17.0.21
      helm:
        valueFiles:
          - $values/applications/wave-01-apps/minio/minio-values.yaml
    - repoURL: https://github.com/jangroth/homekube-apps.git
      targetRevision: HEAD
      ref: values
