apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: http://192.168.86.241
  oidc.config: |
    name: Google (via Dex)
    issuer: https://pi0.taild13083.ts.net/dex
    clientID: argocd
    clientSecret: argocd-dex-client-secret
    requestedScopes:
      - openid
      - profile
      - email
    requestedIDTokenClaims:
      email:
        essential: true
