FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o app ./main.go

FROM scratch

WORKDIR /

COPY --from=builder /app/app .

EXPOSE 8080

CMD ["/app"]    