apiVersion: v1
kind: Namespace
metadata:
  name: cilium-test
  labels:
    app: cilium-test

---
apiVersion: v1
kind: Pod
metadata:
  name: cilium-test-pod
  namespace: cilium-test
  labels:
    app: cilium-test
spec:
  containers:
    - name: cilium-test-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cilium-test
  namespace: cilium-test
  name: cilium-test-nodeport
spec:
  type: NodePort
  selector:
    app: cilium-test
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32767

status:
  loadBalancer: {}
