apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test2
  name: test2
  namespace: play2
spec:
  containers:
    - image: nginx
      name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
