apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-patch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  sources:
    - repoURL: https://github.com/jangroth/homekube-apps.git
      path: applications/wave-00-init/coredns-patch
      targetRevision: HEAD
