apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    wave: "00"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.11.2
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        longhornManager:
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        defaultSettings:
          defaultDataPath: "/storage"
          defaultReplicaCount: 2
          systemManagedCSIComponentsResourceLimits: >-
            {"csi-attacher":{"requests":{"cpu":"25m","memory":"32Mi"},"limits":{"cpu":"50m","memory":"64Mi"}},"csi-provisioner":{"requests":{"cpu":"25m","memory":"32Mi"},"limits":{"cpu":"50m","memory":"64Mi"}},"csi-resizer":{"requests":{"cpu":"25m","memory":"32Mi"},"limits":{"cpu":"50m","memory":"64Mi"}},"csi-snapshotter":{"requests":{"cpu":"25m","memory":"32Mi"},"limits":{"cpu":"50m","memory":"64Mi"}},"longhorn-csi-plugin":{"requests":{"cpu":"50m","memory":"64Mi"},"limits":{"cpu":"100m","memory":"128Mi"}},"node-driver-registrar":{"requests":{"cpu":"10m","memory":"16Mi"},"limits":{"cpu":"25m","memory":"32Mi"}},"longhorn-liveness-probe":{"requests":{"cpu":"10m","memory":"16Mi"},"limits":{"cpu":"25m","memory":"32Mi"}}}
        persistence:
          defaultClassReplicaCount: 2
