apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    wave: "00"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.9.1
    path: applications/wave-00-init/longhorn
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultDataPath: "/storage"
          defaultReplicaCount: 2
        persistence:
          defaultClassReplicaCount: 2
