apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    wave: "01"
  annotations:
    argocd.argoproj.io/sync-wave: "01"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.12.0
    helm: # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
      values: |
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  resources:
                    requests:
                      storage: 50Gi
            serviceMonitorSelectorNilUsesHelmValues: false
          service:
            type: NodePort
            nodePort: 30002
        grafana:
          service:    
            type: NodePort
            nodePort: 30003
          grafana.ini:
            date_formats:
              default_timezone: Australia/Sydney
        alertmanager:
          enabled: true
          service:
            type: NodePort
            nodePort: 30004
