# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    wave: "01"
  annotations:
    argocd.argoproj.io/sync-wave: "01"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.40.0
    helm:
      values: |
        loki:
          # Enable and configure persistent storage
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 20Gi

        # Configure Loki to run in a simple, monolithic mode for a single cluster
        config:
          auth_enabled: false
          server:
            http_listen_port: 3100
            grpc_listen_port: 9095
          
          # This is the section that was missing
          storage:
            type: filesystem
            filesystem:
              directory: /data/loki
          
          schema_config:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                index:
                  prefix: loki_index_
                  period: 24h
                schema: v11

        singleBinary:
          extraVolumeMounts:
            - name: data
              mountPath: /data
          extraVolumes:
            - name: data
              persistentVolumeClaim:
                claimName: loki-loki-persistent-volume-claim
