# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    wave: "01"
  annotations:
    argocd.argoproj.io/sync-wave: "01"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.41.1
    helm:
      # https://grafana.com/docs/loki/latest/setup/install/helm/reference/
      values: |
        # CRITICAL FIX 1: Explicitly set the deployment mode
        deploymentMode: SingleBinary

        # CRITICAL FIX 2: Explicitly set replicas to 0 for the three primary distributed components
        querier:
          replicas: 0
        ingester:
          replicas: 0
        distributor:
          replicas: 0

        # Only enable the single binary mode
        singleBinary:
          replicas: 1
          
        loki:
          # 1. Dummy bucket names (required to pass storage template check)
          storage:
            bucketNames:
              chunks: "dummy-bucket-name"
              ruler: "dummy-ruler-name"
              admin: "dummy-admin-name"
              
          # 2. Persistence for the local PVC
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 20Gi

          # 3. Configuration (using the pipe fix)
          config: |
            auth_enabled: false

            server:
              http_listen_port: 3100
            
            storage_config:
              boltdb_shipper:
                active_index_directory: /loki/index
                cache_location: /loki/cache
                shared_store: filesystem
              filesystem:
                directory: /loki/data
            
            schema_config:
              configs:
                - from: 2020-10-24
                  store: boltdb-shipper
                  object_store: filesystem
                  index:
                    prefix: index_
                    period: 24h
                  schema: v11

      # loki:
      #   # deploymentMode: SingleBinary

      #   storage:
      #     type: filesystem
      #     filesystem:
      #       chunks_directory: /var/lib/loki/chunks # Or your desired path for chunk data
      #       rules_directory: /var/lib/loki/rules # Or your desired path for ruler rules

      #   schemaConfig:
      #     configs:
      #       - from: "2025-01-01"
      #         index:
      #           period: 24h
      #           prefix: index_
      #         object_store: filesystem
      #         schema: v13
      #         store: tsdb

      #   commonConfig:
      #     replication_factor: 1 # For single-node local storage

      #   ingester:
      #     chunk_encoding: snappy
