apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-extras
  namespace: argocd
  labels:
    wave: "01"
  annotations:
    argocd.argoproj.io/sync-wave: "01"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/jangroth/homekube-apps.git
      path: applications/wave-01-apps/longhorn-extras
      targetRevision: HEAD
