apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  labels:
    wave: "01"
  annotations:
    argocd.argoproj.io/sync-wave: "01"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.0.21
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        auth:
          rootUser: admin
          rootPassword: admin1234

        persistence:
          enabled: true
          storageClass: longhorn
          size: 50Gi # Allocate space for your logs

        service:
          type: ClusterIP
          port: 9000

        image:
          repository: bitnamilegacy/minio 
          tag: latest

        console:
          image:
            repository: bitnamilegacy/minio-object-browser
            tag: latest
          service:
            type: NodePort
            nodePorts:
              http: 30005
