apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-lb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jangroth/homekube-apps.git
    path: applications/wave-01-apps/test-lb
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test-lb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
