apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    io.cilium/lb-ipam-ips: "192.168.86.245"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: homepage
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
