apiVersion: v1
kind: Service
metadata:
  name: cst-longhorn-ui
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn-ui
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/component: ui
    app.kubernetes.io/managed-by: argocd
  annotations:
    io.cilium/lb-ipam-ips: "192.168.86.242"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: longhorn-ui
status:
  loadBalancer: {}
