apiVersion: v1
kind: Service
metadata:
  name: cst-argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
status:
  loadBalancer: {}
